feat: read cloud creds for obstore from env
stac-utils/stac-rs pull request #556
Opened 2024-12-05 15:10 UTC by alekzvik

## Closes

- #414 

## Description

This is POC.

Right now we init `object_store` in `format.rs`. 
We use `object_store::parse_url_opts` function that parses the URL, extracts store kind, bucket, etc from it and builds a store from it. 

I yanked this function to change one line in a macro from `builder::new()` to `buidler::from_env()`
Pros:
+ do not need to think about the env reusing the builder logic there
+ do not need to explicitly make a store object we interact with

Cons:
- still create a new `ObjectStore` for each `format.get_opts()` call
- reads env a lot 

Alternatives I would be happy to discuss:
- making `object_store` more of an explicit item inside the code base, separating it from `format` and maybe starting to pass it around (e.g. init in cli entrypoint, pass down to others)
- adding some long-living pool of per-bucket/creds object stores that are instantiated and utilized implicitly.
- (the worst) a bit hacky way, where in cli entrypoint  we can read the env for all cloud providers that are enabled by features and either read the env explicitly or use builders to extract the creds and then pass it on as opts, like this:
```
builder = S3Builder::from_env()
if let Some(value) = builder.aws_access_key {
  opts.insert("aws_access_key", value)
}
```

Overall, I'd like to discuss if it is a good approach to the problem or if you have other possible directions to explore.

## Checklist

Delete any checklist items that do not apply (e.g. if your change is minor, it may not require documentation updates).

- [ ] Unit tests
- [ ] Documentation, including doctests
- [ ] Git history is linear
- [ ] Commit messages are descriptive
- [ ] (optional) Git commit messages follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Code is formatted (`cargo fmt`)
- [ ] `cargo test`
- [ ] Changes are added to the CHANGELOG

2024-12-10 12:07 UTC, alekzvik commented
I have not finished dealing with errors in this, but I want your initial opinion to see if I should proceed in this direction. (hence the failing tests)

2024-12-11 13:12 UTC, gadomski reviewed
Generally looks good! I think I'd prefer a struct-specific cache instead of a global one. So maybe a `ObjectStore` structure that holds the cache?

2024-12-11 13:13 UTC, gadomski commented
> The test failures are unrelated and due to 403 HTTP error in validation (should we mock the schema query there to be less dependent on the internet?)

Yeah, I've run into this before, I forget how I solved it initially (it's something to do with cloudflare being cranky about our requests for something that's a redirect). While I do want to test network-based validation (the STAC ecosystem does it a lot) I agree that network-based tests are fragile and bad. I'd be down for even just ignoring them for now and adding a tracking issue to fix.

2024-12-12 00:24 UTC, gadomski commented
> If we put the cache in a struct, who will be responsible for creating it? How do I make it outlive the get_opts and put_opts functions so that they can both reuse the same store?

Yup, it's a good call-out. I'd like to expand our API to include `stac::ObjectStore` or some-such, a structure that folks can use to get and put STAC things. `get_opts` would create a oneshot instation of `ObjectStore` to do its request and then destroy it.

This mirrors the pattern of stuff like **reqwests**, which has `reqwests::get` for a single-use, and a `Client` for multi-use.

2024-12-12 13:39 UTC, alekzvik commented
ok, now I understand what you want.

Let me explain why I think global cache is a better approach.

Before implementing this, I looked at who uses the `object_store` crate and how. Two examples jumped out: `datafusion` & `polars`. Both have the same concept of a `cache` for `object_store` clients but approach it differently. 

## Datafusion
The main `datafusion` interaction pattern is to create a `SessionContext` and interact with it. See [example from docs](https://datafusion.apache.org/user-guide/example-usage.html#run-a-sql-query-against-data-stored-in-a-csv). This is very similar to the pattern with a session that reqwest uses. The context holds a `RuntimeEnv` ([source](https://github.com/apache/datafusion/blob/08119e634e1740801bf543d8106f92de340ec011/datafusion/execution/src/runtime_env.rs#L70-L79)) that has a pool for object stores ([source](https://github.com/apache/datafusion/blob/main/datafusion/execution/src/object_store.rs#L149-L167)). Stores are identified by a base URL and you can and must register them in advance. By default. only file-based `object_store` is initialized. If you want to use cloud storage, you need to register the store explicitly.

## Polars
Polars' main interaction pattern is different, you deal with data frames. Dataframes can be read from wherever. So, they build object stores based on a URL ([source](https://github.com/pola-rs/polars/blob/main/crates/polars-io/src/cloud/object_store_setup.rs#L200-L209)) and use global cache ([source](https://github.com/pola-rs/polars/blob/main/crates/polars-io/src/cloud/object_store_setup.rs#L19-L21)).

## stac-rs
I would argue that our use cases and interaction pattern are much closer to `polars` than `datafusion`. I would even go one step further, and say that it is more dynamic. 

Our main "object" that we interact with is STAC. There is a recommendation that STACs should be colocated, but no guarantees. Consider the following example. I am working with a public STAC of raster imagery, I apply a set of filters, produce a new collection, and save it to my cloud storage. My collection is located in one bucket, my items are in a different bucket. This is a valid STAC, that we must deal with. When I receive a collection, there is no way for me to construct an `object_store` in advance, as I do not know where all the links would lead.

Because of the dynamic nature of the STAC, it can potentially be located in more than one bucket (or even cloud provider). At the same time, STAC as a format can have huge amounts of files. So, I would argue we need to focus on both the dynamic aspect of reacting to new locations and optimization to be able to fetch multiple files effectively. I guess the main point is, that we never have a guarantee that one object store is enough, so we need to be prepared to work with multiple. And exposing this outside seems cumbersome.

## Alternative API
Let's try to explore the alternative, where we expose the registry that lives in its own trait and has a more limited lifetime
```
let url = URL::parse("<some stac url>");
let registry = ObjectStoreRegistry::new();
registry.register_store(url);
let value = stac::io::get(url, registry);
for link in value.links() {
    ???
}
```
In this example, if we use the `datafusion` approach, we need to somewhere decide if we need to create a new store. It seems that exposing the `ObjectStoreRegistry` does not give any benefits but rather more cumbersome interactions.

## Conclusion
Given all of the above, I chose the global cache approach, as it is flexible enough, the implementation is straightforward, and user interaction is streamlined.
### Pros
- You can always use options to adjust the underlying store. 
```
let value = stac::io::get_opts(stac_url, vec![("aws_secret", "****")]);
```
- If you do not need to think about object stores, you do not have to

### Cons
- This cache trickery is implicit. Implicit things are usually bad. But I would argue, that in this case, as a user of a library, I do not want to deal with multiple object stores and rather focus on STACs
- Typing and explicit/implicit choice. While you still have a way to configure your object store, it is all based on a "vec of tuples of strings", and you do not benefit from type checks. The alternative, where you can construct your own object store seems more robust. We can consider adding another function that accepts an object store and does IO with it or adds it to the cache.

2024-12-18 00:55 UTC, gadomski commented
I don't hate that, and I agree that we're more likely to be used in a **polars**-style use case. Thanks for writing it out.

Since it is so tricky, my initial instinct is to make a new crate for it, so we don't have to break the core crate's semver when we (inevitably) change everything.

2024-12-21 23:26 UTC, alekzvik commented
Changes since last time:
- Move the code to a separate crate
- Add new crate to CI
- use the crate in `core` under already used `object-store` feature

Please let me know if anything can be improved.

Oh, and also, at some point I merged the main in my branch, then I saw that merge commits are not allowed, so I rebased and force-pushed. At this point, the history is linear, but merging is still blocked. Is there anything I can do?

2024-12-23 03:22 UTC, gadomski requested changes
Seems reasonable to me, requested a couple of changes. However, doesn't seem to work:

```shell
cargo run --all-features -- translate https://raw.githubusercontent.com/radiantearth/stac-spec/refs/heads/master/examples/simple-item.json
```

This command works on **main**.

2024-12-23 03:22 UTC, gadomski commented on crates/object-store-cache/src/cache.rs
> +// The value does not have any meaning, other than polars use the same.
Can you link to the **polars** code that uses it? Credit where credit is due.

2024-12-23 03:22 UTC, gadomski commented on crates/object-store-cache/src/cache.rs
> +    /// A base url to the bucket.
It's not always a bucket, right? I.e. Azure doesn't call them buckets.

2024-12-23 03:22 UTC, gadomski commented on crates/object-store-cache/src/cache.rs
> +            return Ok((store.clone(), path));
Can you add some `tracing::debug` statements here and Below when we write to (and sometimes clear) the cache?

2024-12-23 03:22 UTC, gadomski commented on crates/object-store-cache/src/cache.rs
> +
```suggestion
```

2024-12-23 03:22 UTC, gadomski commented on crates/object-store-cache/src/cache.rs
> +        // let options2: Vec<(String, String)> = vec![(String::from("some"), String::from("option"))];
```suggestion
```

2024-12-23 03:22 UTC, gadomski commented on crates/object-store-cache/src/lib.rs
> +//!  - read cloud creadentials from env
```suggestion
//!  - Read cloud credentials from your environment
```

2024-12-23 03:22 UTC, gadomski commented on crates/object-store-cache/src/lib.rs
> +//!  - cache used objects_stores based on url and options
```suggestion
//!  - Cache used object stores based on url and options
```

2024-12-23 03:23 UTC, gadomski commented
Also, as a note, nothing about this is general to STAC, so we should keep an eye on either **object-store** or another package to provide this for us ... e.g. if someone could rip out the **polars** stuff to its own crate.

2025-04-17 11:53 UTC, gadomski commented
Going to close this as OBE by https://github.com/stac-utils/stac-rs/pull/642, but please feel free to re-open if there's more that we can add!

2025-04-17 11:53 UTC, closed without merging